
name: Publish
on:
  push:
    tags: v*.*.*
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.7
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
    - name: Run tests
      env:
          QVAPAY_APP_ID: ${{ secrets.QVAPAY_APP_ID }}
          QVAPAY_APP_SECRET: ${{ secrets.QVAPAY_APP_SECRET }}
      run: make tests
    - name: Run build
      run: poetry build
    - name: Publish in GitHub Releases
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    - name: Publish in PyPI
      uses: d1618033/gh-action-python-publish-using-poetry@master
      with:
        pypi_username: ${{ secrets.PYPI_USERNAME }}
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
